name: gha-auto-dependabot-rebase
author: Bill Beesley <bill@beesley.dev>
description: Github Action to automatically request dependabot rebases
inputs:
  task:  # id of input
    description: 'Which task to perform (rebase, recreate)'
    required: false
    default: 'rebase'
branding:
  icon: box
  color: blue
runs:
  using: 'node16'
  main: 'dist/main.cjs'