name: Build & Test Common
on:
  workflow_call:
    inputs:
      actor:
        required: true
        type: string
      ref:
        required: true
        type: string
      commit:
        required: true
        type: string
      is_main_branch:
        required: true
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            dist
          key: ${{ inputs.commit }}-test
      - name: install
        run: |
          npm ci
      - name: test
        run: npm test
